### IMPA 
### Professor: Vitor Guerra
### Monitor: Pedro
### Aluno: Diego Dias 
### Projeto: Exercicio 1

Pare esse exercício serão disponibilizados três arquivos: ***amazonas.csv*** que contém dados históricos de desflorestamento nos municipios do Amazonas no ano de 2014, ***estados.csv*** que contém uma lista com o nome, uf e codigo dos estados brasileiros e ***municipios.csv*** que contém o nome de todos os municípios brasileiros e suas respectivas localizações no globo (longitude e latitude).

### Importando as bibliotecas

In [7]:
import folium #biblioteca para plot mapa 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math
import csv #bibliotecas para arquivos  csv
### Começaremos importando todas as tabelas
#amazonas
dados1 = pd.read_csv('amazonas.csv',encoding='utf-8')
dados1.head()

,Municípios,Agricultura Anual,Área não Observada,Área Urbana,Desflorestamento 2014,Floresta,Hidrografia,Mineração,Mosaico de Ocupações,Não Floresta,Outros,Pasto com Solo Exposto,Pasto Limpo,Pasto Sujo,Reflorestamento,Regeneração com Pasto,Vegetação Secundária,Total Geral
0,Alvaraes,NaN,0.07,1.90,2.75,"5,415.56",133.87,NaN,101.08,43.26,5.36,NaN,2.92,1.02,NaN,5.13,198.55,"5,911.46"
1,Amatura,NaN,NaN,2.05,0.36,"4,220.22",209.41,NaN,15.87,216.55,3.76,NaN,4.03,NaN,NaN,11.44,71.74,"4,755.42"
2,Anama,NaN,0.86,0.89,0.44,"2,001.85",229.30,NaN,6.90,34.81,13.11,NaN,2.02,0.87,NaN,NaN,160.61,"2,451.66"
3,Anori,NaN,0.15,2.77,0.59,"4,646.53",436.07,NaN,17.12,636.01,4.70,NaN,8.05,0.52,NaN,NaN,41.98,"5,794.49"
4,Apui,NaN,6.71,5.91,80.19,"51,396.43",213.50,NaN,8.76,622.87,7.18,NaN,812.61,329.85,NaN,208.13,546.18,"54,238.32"

In [38]:
#Identificando linhas nulas 
#identificando dados faltantes

dados1.isnull().sum()

Municípios                 0
Agricultura Anual         52
Área não Observada         4
Área Urbana                0
Desflorestamento 2014      0
Floresta                   0
Hidrografia                0
Mineração                 47
Mosaico de Ocupações       0
Não Floresta               1
Outros                     0
Pasto com Solo Exposto    55
Pasto Limpo                2
Pasto Sujo                 4
Reflorestamento           60
Regeneração com Pasto      3
Vegetação Secundária       0
Total Geral                0
dtype: int64

In [9]:
### Começaremos importando todas as tabelas 
#tabelas estado 
dados2 = pd.read_csv('estados.csv', encoding='utf-8')
dados2.head()

   codigo_uf  uf      nome
0         11  RO  Rondônia
1         12  AC      Acre
2         13  AM  Amazonas
3         14  RR   Roraima
4         15  PA      Pará

In [37]:
#Identificando linhas nulas 
#identificando dados faltantes

dados2.isnull().sum()

codigo_uf    0
uf           0
nome         0
dtype: int64

In [8]:
### Começaremos importando todas as tabelas 
dados3 = pd.read_csv('municipios.csv', encoding='utf-8')
dados3.head()

,i>>?codigo_ibge,nome,latitude,longitude,capital,codigo_uf
0,5200050,Abadia de GoiA!s,-16.75730,-49.4412,0,52
1,3100104,Abadia dos Dourados,-18.48310,-47.3916,0,31
2,5200100,AbadiAC/nia,-16.19700,-48.7057,0,52
3,3100203,AbaetA(c),-19.15510,-45.4444,0,31
4,1500107,Abaetetuba,-1.72183,-48.8788,0,15

In [39]:
#Identificando linhas nulas 
#identificando dados faltantes

dados3.isnull().sum()

codigo_ibge    0
nome           0
latitude       0
longitude      0
capital        0
codigo_uf      0
dtype: int64

Apos carregar os dados devemos associar as tabelas de estados e municípios e selecionar apenas os municípios do Amazonas.

In [10]:
#Vamos combinar os dois DataFrames,  o campo  "codigo-uf", do 
#primeiro equivale ao campo "codigo_uf" do segundo 
pib_ddd = dados2.merge(dados3, left_on='codigo_uf', right_on = 'codigo_uf')
pib_ddd

,codigo_uf,uf,nome_x,i>>?codigo_ibge,nome_y,latitude,longitude,capital
0,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,-11.92830,-61.9953,0
1,11,RO,Rondônia,1100379,Alto Alegre dos Parecis,-12.13200,-61.8350,0
2,11,RO,Rondônia,1100403,Alto ParaAso,-9.71429,-63.3188,0
3,11,RO,Rondônia,1100346,Alvorada D'Oeste,-11.34630,-62.2847,0
4,11,RO,Rondônia,1100023,Ariquemes,-9.90571,-63.0325,0
5,11,RO,Rondônia,1100452,Buritis,-10.19430,-63.8324,0
6,11,RO,Rondônia,1100031,Cabixi,-13.49450,-60.5520,0
7,11,RO,Rondônia,1100601,CacaulAC/ndia,-10.34900,-62.9043,0
8,11,RO,Rondônia,1100049,Cacoal,-11.43430,-61.4562,0
9,11,RO,Rondônia,1100700,Campo Novo de RondA'nia,-10.57120,-63.6266,0
10,11,RO,Rondônia,1100809,Candeias do Jamari,-8.79070,-63.7005,0
11,11,RO,Rondônia,1100908,Castanheiras,-11.42530,-61.9482,0
12,11,RO,Rondônia,1100056,Cerejeiras,-13.18700,-60.8168,0
13,11,RO,Rondônia,1100924,Chupinguaia,-12.56110,-60.8877,0
14,11,RO,Rondônia,1100064,Colorado do Oeste,-13.11740,-60.5454,0
15,11,RO,Rondônia,1100072,Corumbiara,-12.95510,-60.8947,0
16,11,RO,Rondônia,1100080,Costa Marques,-12.43670,-64.2280,0
17,11,RO,Rondônia,1100940,Cujubim,-9.36065,-62.5846,0
18,11,RO,Rondônia,1100098,EspigAPSo D'Oeste,-11.52660,-61.0252,0
19,11,RO,Rondônia,1101005,Governador Jorge Teixeira,-10.61000,-62.7371,0
20,11,RO,Rondônia,1100106,GuajarA!-Mirim,-10.78890,-65.3296,0
21,11,RO,Rondônia,1101104,ItapuAPS do Oeste,-9.19687,-63.1809,0
22,11,RO,Rondônia,1100114,Jaru,-10.43180,-62.4788,0
23,11,RO,Rondônia,1100122,Ji-ParanA!,-10.87770,-61.9322,0
24,11,RO,Rondônia,1100130,Machadinho D'Oeste,-9.44363,-61.9818,0
25,11,RO,Rondônia,1101203,Ministro Andreazza,-11.19600,-61.5174,0
26,11,RO,Rondônia,1101302,Mirante da Serra,-11.02900,-62.6696,0
27,11,RO,Rondônia,1101401,Monte Negro,-10.24580,-63.2900,0
28,11,RO,Rondônia,1100148,Nova BrasilAC/ndia D'Oeste,-11.72470,-62.3127,0
29,11,RO,Rondônia,1100338,Nova MamorA(c),-10.40770,-65.3346,0
...,...,...,...,...,...,...,...,...
5540,52,GO,Goiás,5220108,SAPSo LuAs de Montes Belos,-16.52110,-50.3726,0
5541,52,GO,Goiás,5220157,SAPSo Luiz do Norte,-14.86080,-49.3285,0
5542,52,GO,Goiás,5220207,SAPSo Miguel do Araguaia,-13.27310,-50.1634,0
5543,52,GO,Goiás,5220264,SAPSo Miguel do Passa Quatro,-17.05820,-48.6620,0
5544,52,GO,Goiás,5220280,SAPSo PatrAcio,-15.35000,-49.8180,0
5545,52,GO,Goiás,5220405,SAPSo SimAPSo,-18.99600,-50.5470,0
5546,52,GO,Goiás,5220454,Senador Canedo,-16.70840,-49.0914,0
5547,52,GO,Goiás,5220504,SerranA3polis,-18.30670,-51.9586,0
5548,52,GO,Goiás,5220603,SilvAC/nia,-16.66000,-48.6083,0
5549,52,GO,Goiás,5220686,SimolAC/ndia,-14.46440,-46.4847,0
5550,52,GO,Goiás,5220702,SAtio d'Abadia,-14.79920,-46.2506,0
5551,52,GO,Goiás,5221007,Taquaral de GoiA!s,-16.05210,-49.6039,0
5552,52,GO,Goiás,5221080,Teresina de GoiA!s,-13.78010,-47.2659,0
5553,52,GO,Goiás,5221197,TerezA3polis de GoiA!s,-16.39450,-49.0797,0
5554,52,GO,Goiás,5221304,TrAas Ranchos,-18.35390,-47.7760,0
5555,52,GO,Goiás,5221403,Trindade,-16.65170,-49.4927,0
5556,52,GO,Goiás,5221452,Trombas,-13.50790,-48.7417,0
5557,52,GO,Goiás,5221502,TurvAC/nia,-16.61250,-50.1369,0
5558,52,GO,Goiás,5221551,TurvelAC/ndia,-17.85020,-50.3024,0
5559,52,GO,Goiás,5221577,Uirapuru,-14.28350,-49.9201,0
5560,52,GO,Goiás,5221601,UruaASSu,-14.52380,-49.1396,0
5561,52,GO,Goiás,5221700,Uruana,-15.49930,-49.6861,0
5562,52,GO,Goiás,5221809,UrutaA,-17.46510,-48.2015,0
5563,52,GO,Goiás,5221858,ValparaAso de GoiA!s,-16.06510,-47.9757,0
5564,52,GO,Goiás,5221908,VarjAPSo,-17.04710,-49.6312,0
5565,52,GO,Goiás,5222005,VianA3polis,-16.74050,-48.5159,0
5566,52,GO,Goiás,5222054,VicentinA3polis,-17.73220,-49.8047,0
5567,52,GO,Goiás,5222203,Vila Boa,-15.03870,-47.0520,0
5568,52,GO,Goiás,5222302,Vila PropAcio,-15.45420,-48.8819,0
5569,53,DF,Distrito Federal,5300108,BrasAlia,-15.77950,-47.9297,1

Note que nos dados provenientes da tabela municipios.csv o nome dos municípios estão todos acentuados, no entanto na tabela amazonas os nomes estão sem acento. Logo é necessario remover os acentos dos nomes da tabela municipios.csv.

In [16]:
# -*- coding: latin-1 -*-
# -*- coding: UTF-8 -*-

# remover acentos 
import unidecode
import csv
import pandas as pd
import sys 


def remove_acentos(feed):
  # abrir o arquivo
  csv_f = open(feed, encoding="latin-1", mode='r')
  #ler o arquivo 
  csv_str = csv_f.read()
  csv_str_remove_acento = unidecode.unidecode(csv_str)
  csv_f.close()
  csv_f = open(feed, 'w')
  csv_f.write(csv_str_remove_acento)
  return True

if __name__ == "__main__":
    
    remove_acentos('municipios.csv')
    print(csv_f)
    
    
# Verificar se está certo

      i>>?codigo_ibge                   nome  latitude  longitude  capital  \
0             5200050       Abadia de GoiA!s -16.75730   -49.4412        0
1             3100104    Abadia dos Dourados -18.48310   -47.3916        0
2             5200100            AbadiAC/nia -16.19700   -48.7057        0
3             3100203              AbaetA(c) -19.15510   -45.4444        0
4             1500107             Abaetetuba  -1.72183   -48.8788        0
5             2300101                Abaiara  -7.34588   -39.0416        0
6             2900108                 AbaAra -13.24880   -41.6619        0
7             2900207               AbarA(c)  -8.72073   -39.1162        0
8             4100103                AbatiA! -23.30490   -50.3133        0
9             4200051          Abdon Batista -27.61260   -51.0233        0
10            1500131        Abel Figueiredo  -4.95333   -48.3933        0
11            4200101           Abelardo Luz -26.57160   -52.3229        0
12            3100302             Abre Campo -20.29960   -42.4743        0
13            2600054           Abreu e Lima  -7.90072   -34.8984        0
14            1700251          AbreulAC/ndia  -9.62101   -49.1518        0
15            3100401                Acaiaca -20.35900   -43.1439        0
16            2100055         AASSailAC/ndia  -4.94714   -47.5004        0
17            2900306              Acajutiba -11.65750   -38.0197        0
18            1500206                 AcarA!  -1.95383   -48.1985        0
19            2300150                Acarape  -4.22083   -38.7055        0
20            2300200                AcaraAo  -2.88769   -40.1183        0
21            2400109                  Acari  -6.42820   -36.6347        0
22            2200053                AcauAPS  -8.21954   -41.0831        0
23            4300034                AceguA! -31.86650   -54.1615        0
24            2300309               Acopiara  -6.08911   -39.4480        0
25            5100102               Acorizal -15.19400   -56.3632        0
26            1200013           AcrelAC/ndia  -9.82581   -66.8972        0
27            5200134               AcreAona -17.39600   -50.3749        0
28            2400208                  AASSu  -5.58362   -36.9140        0
29            3100500              AASSucena -19.06710   -42.5419        0
...               ...                    ...       ...        ...      ...
5540          1508357      VitA3ria do Xingu  -2.87922   -52.0088        0
5541          4128708               Vitorino -26.26830   -52.7843        0
5542          2113009        Vitorino Freire  -4.28184   -45.2505        0
5543          3172103           Volta Grande -21.76710   -42.5375        0
5544          3306305          Volta Redonda -22.52020   -44.0996        0
5545          3557006             Votorantim -23.54460   -47.4388        0
5546          3557105            Votuporanga -20.42370   -49.9781        0
5547          2933406                 Wagner -12.28190   -41.1715        0
5548          2211704            Wall Ferraz  -7.23151   -41.9050        0
5549          1722081         WanderlAC/ndia  -6.85274   -47.9601        0
5550          2933455              Wanderley -12.11440   -43.8958        0
5551          3172202         Wenceslau Braz -22.53680   -45.3626        0
5552          4128500         Wenceslau Braz -23.87420   -49.8032        0
5553          2933505  Wenceslau GuimarAPSes -13.69080   -39.4762        0
5554          4323770             WestfA!lia -29.42630   -51.7645        0
5555          4219408              Witmarsum -26.92750   -49.7947        0
5556          1722107               XambioA!  -6.41410   -48.5320        0
5557          4128807                XambrAa -23.73640   -53.4884        0
5558          4323804             Xangri-lA! -29.80650   -50.0519        0
5559          4219507               XanxerAa -26.87470   -52.4036        0
5560          1200708                 Xapuri -10.65160   -68.4969        0
5561          4219606              Xavantina -27.06670   -52.3430        0
5562          4219705                  Xaxim -26.95960   -52.5374        0
5563          2616506               XexA(c)u  -8.80460   -35.6212        0
5564          1508407               Xinguara  -7.09830   -49.9437        0
5565          2933604            Xique-Xique -10.82300   -42.7245        0
5566          2517407                ZabelAa  -8.07901   -37.1057        0
5567          3557154               Zacarias -21.05060   -50.0552        0
5568          2114007             ZA(c) Doca  -3.27014   -45.6553        0
5569          4219853              ZortA(c)a -27.45210   -51.5520        0

      codigo_uf
0            52
1            31
2            52
3            31
4            15
5            23
6            29
7            29
8            41
9            42
10           15
11           42
12           31
13           26
14           17
15           31
16           21
17           29
18           15
19           23
20           23
21           24
22           22
23           43
24           23
25           51
26           12
27           52
28           24
29           31
...         ...
5540         15
5541         41
5542         21
5543         31
5544         33
5545         35
5546         35
5547         29
5548         22
5549         17
5550         29
5551         31
5552         41
5553         29
5554         43
5555         42
5556         17
5557         41
5558         43
5559         42
5560         12
5561         42
5562         42
5563         26
5564         15
5565         29
5566         25
5567         35
5568         21
5569         42

[5570 rows x 6 columns]


Em seguida relacione as tabelas municipios e amazonas.

In [13]:
#relacionar tabelas

# Questão
Plote no mapa do Brasil indicadores de desflorestamento para todos os municipios do amazonas. Os indicadores devem ser relativos ao tamanho da floresta de cada município dando destaque aos municipios que com desflorestamento acima da média.

Dica
O desflorestamento relativo é dado pelas colunas Desflorestamento 2014 / Floresta da tabela amazonas.csv. Note que a coluna Floresta não é numérica e contém ',' separando os milhares, sendo necessário remover a ',' de todas as entradas e logo após converter os valores para float.

Podem ser usadas todas as dicas relevantes sobre apresentação de figuras nos textos Making Data Meaningful e Ten Simple Rules for Better Figures.

Para plotar sobre o mapa, pode-se usar a funções normais do matplotlib e ao fim chamar a função mplleaflet.display()

In [17]:
#calcula as informações do desflorestamento
import pandas as pd
import folium
#Coordenada retiradas do Google Maps 
brasil = folium.Map(location =[-16.1237611, -59.9219642], zoom_start=4)
brasil

In [30]:
import pandas as pd 
import folium
mapa_amazonas = pd.read_csv('amazonas.csv')
#Dúvida
#mapa_amazonas1 = mapa_amazonas.iloc[0]
#folium.Marker(
      #location=[mapa_amazonas1['latitude'], mapa_amazonas1['longitude']],
#).add_to(brasil)

In [19]:
#codigo de plot
#Dúvida
#plt.figure(figsize=(8,8))

#plt.plot([1], [1], 'o')

#transforma o plot em localizações no mapa
#mplleaflet.display()

# Questão

Segundo os dados, a mineração nos municípios tem alguma relação com o desflorestamento acima da média? Mostre suas conclusões por tabelas e plots no mapa.

In [10]:
#calcula as relaçoes entre desflorestamento e mineração
#Dúvida

In [11]:
# conclusoes sobre mineração e desflorestamento
#Dúvidaa

In [18]:
#codigo de plot
#Dúvida
#plt.figure(figsize=(8,8))



#transforma o plot em localizações no mapa

### Referências:

[1] INPE, Monitoramento da Amazônia.Disponível em:< http://www.inpe.br/noticias/noticia.php?Cod_Noticia=4829 >. Acesso 02 Set, 2019.

[2]Unidades de Conservação,Refúgio de Vida Silvestre Metrópole da Amazônia. Disponível em:<https://uc.socioambiental.org/arp/5124>.Acesso 08 Set,2019.

[3]INPE,Estimativa de emissões dos gases do efeito estufa. Disponível em:<http://dados.gov.br/dataset/inpe-em>. Acesso 08 Set, 2019.

[4]Folium, Visualizar Dados.Disponível em: <https://python-visualization.github.io/folium/index.html>. Acesso 08 Set, 2019.